// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExploreContainer: typeof import('./components/ExploreContainer.vue')['default']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
